### ISSUE TITLE
Generate a directory of URLs created

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#17]
#### Description

Our plan is to generate a unique URL for each organization that begins the transformation process. This unique URL will allow organizations to initiate the process, pause, and pick up where they left off---as long as they have the URL.

Once the transformation process is complete, this URL will serve as a home for static PLATS-data, as well as its OSM-ready variant, for download and use by third-parties.

To advance both of those goals, let's provide a directory of URLs generated, the name of the organization that owns the URL, and the status (complete or in progress) of the transformation.
#### Tasks
- [ ] Create scheme for generating unique URLs based on agency information
- [ ] Design a table for inclusion on the home page--determine columns, number of rows per page, etc.
- [ ] Decide whether organizations should have control over whether their URL shows up in the directory while it the transformation is "in progress".

**Comment by ondrae** [comment]
We can use S3 as our directory here. We'll pull down the list of folders and display links to each one from our service.
How to: http://stackoverflow.com/questions/17375127/how-can-i-get-list-of-only-folders-in-amazon-3-using-python-boto
