### ISSUE TITLE
Create simplified geojson to show on map

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/OpenTrails#25]
#### Description

Many stewards shapefiles of trail data are huge! They are big enough to really slow down a browser when shown on a map.

We should create a sample-segments.geojson in addition to the full segments.json file. We'd show the sample file on the map.

We can show every 10th trail in a shapefile. We can also simplify the segments with `ogr2ogr -t_srs EPSG:4326 -simplify 500 -f GeoJSON output input`
#### Files

routes.py and transform.py
#### Tasks
- [ ] Open segments.json and copy over every tenth trail.
- [ ] Use ogr2ogr to simplify
- [ ] Save the simplified-segments.geojson in upload.
- [ ] Use this file to create the map

**Comment by junosuarez** [comment]
ogr2ogr is great. I've also used https://www.npmjs.org/package/simplify-geojson for the same task

**Comment by ondrae** [comment]
Thanks @jden, I'll check it out.

**Comment by ondrae** [comment]
I'm thinking a good file structure will be like:

```
/Steward
    /Uploads
        segments.zip
        trailheads.zip
        areas.zip
    /OpenTrails
        stewards.csv
        namedTrails.csv
        trailHeads.geojson
        trailSegments.geojson
        areas.geojson
    /web
        trailHeads-web.geojson
        trailSegments-web.geojson
        areas-web.geojson
```

**Comment by migurski** [comment]
I'd still like to caution against doing anything by steward.
