### ISSUE TITLE
Validate raw trail network data

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/OpenTrails#3]
#### Description

Take in raw trail network data and validate it. Start with python scripts that will eventually become a web service.
#### Tasks
- [ ] Validate trailhead shapefile
- [ ] Validate trail segment shapefile
- [ ] Validate areas shapefile

**Comment by ondrae** [comment]
Using Shapefile to Geojson service OGRE.
curl -F "sourceSrs=EPSG:3734" -F "targetSrs=EPSG:4326" -F "upload=@dummy-data/ohio-data.zip" http://ogre.adc4gis.com/convert

**Comment by alanjosephwilliams** [comment]
#### Description

Perform, or be able to perform, the following tasks for each upload.
- [x] open a shapefile
- [x] change projection
- [x] create geojson
- [ ] display on map

**Comment by migurski** [comment]
Same thing, minus external dependency, assumes that `input.prj` exists:

```
$ ogr2ogr -t_srs EPSG:4326 -f GeoJSON output.geojson input.shp
```

**Comment by migurski** [comment]
Also, prepared OGR/GDAL/GEOS for Heroku: https://github.com/codeforamerica/heroku-buildpack-pygeo

**Comment by alanjosephwilliams** [comment]
@ondrae let's aim to get this on a map today.
